# Dev configuration
server:
  port: 5000
security:
  basic:
    enabled: false
  ignored:
    - /**
management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
  security:
    enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} %clr(%X{username}){magenta} - %clr(%c{10}[%L]){cyan} : %msg%n"
url:
  get_product_by_id: "http://backenddevtest_simulado_1:80/product/"
  get_product_similar_id: "http://backenddevtest_simulado_1:80/product/{productId}/similarids"
swagger:
  url:
    pom: "shared/springboot/integrator/pom.xml"

resilience4j:
  circuitbreaker:
    instances:
      productService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 70
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 5
        waitDurationInOpenState: 10s
        slidingWindowType: COUNT_BASED
  timelimiter:
    instances:
      productService:
        cancelRunningFuture: false
        timeoutDuration: 10s
