# Dev configuration
server:
  port: 5000
security:
  basic:
    enabled: false
  ignored:
    - /**
management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  pattern:
    console: "%d{yyyy-MM-dd hh:mm:ss} %clr(%X{username}){magenta} - %clr(%c{10}[%L]){cyan} : %msg%n"
url:
  get_product_by_id: http://localhost:3001/product/
  get_product_similar_id: http://localhost:3001/product/{productId}/similarids
swagger:
  url:
    pom: "pom.xml"